window.ILM_CAMPUSES = {
  kwasu: { id: 'kwasu', state: 'Kwara State', name: 'KWASU', institution: 'Kwara State University', logo: 'image/university-logo/kwasu.jpg', description: 'ILM Nexus KWASU Campus is a practical student community for digital skills, innovation, and career development.', programs: ['Graphics Design', 'Frontend Development', 'Digital Marketing', 'UI/UX Design'], route: 'state/kwara/kwasu/' },
  unilorin: { id: 'unilorin', state: 'Kwara State', name: 'University of Ilorin', institution: 'University of Ilorin', logo: 'image/university-logo/University_of_Ilorin_logo.jpg', description: 'ILM Nexus University of Ilorin Campus connects learners to practical technology, creative, and career opportunities.', programs: ['Frontend Development', 'Digital Marketing', 'Content Creation'], route: 'state/kwara/unilorin/' },
  alhikmah: { id: 'alhikmah', state: 'Kwara State', name: 'Al-Hikmah University', institution: 'Al-Hikmah University', logo: 'image/university-logo/al-hikmauniveristylogo.jpg', description: 'ILM Nexus Al-Hikmah University Campus supports a growing community of learners and creators.', programs: ['Graphics Design', 'Video Editing', 'Digital Marketing'], route: 'state/kwara/alhikmah/' },
  summit: { id: 'summit', state: 'Kwara State', name: 'Summit University', institution: 'Summit University, Offa', logo: 'image/university-logo/Summit Universitylogo.jpg', description: 'ILM Nexus Summit University Campus builds practical skills through community-led learning and events.', programs: ['Content Creation', 'Frontend Development', 'Programme Management'], route: 'state/kwara/summit-university/' },
  'muhamad-kalmardeen': { id: 'muhamad-kalmardeen', state: 'Kwara State', name: 'Muhamad Kalmardeen University', institution: 'Muhamad Kalmardeen University', logo: 'image/university-logo/mku logo.jpg', description: 'ILM Nexus Muhamad Kalmardeen University Campus is preparing students for digital opportunities.', programs: [], route: 'state/kwara/muhamad-kalmardeen/' },
   'Federal University of Health Sciences, Azare (FUHSA)': { id: 'fuhsa', state: ' State', name: 'Federal University of Health Sciences, Azare', institution: 'Federal University of Health Sciences, Azare', logo: 'image/university-logo/fuhsa logo.jpg', description: 'ILM Nexus Federal University of Health Sciences, Azare Campus supports practical digital learning and campus community.', programs: [], route: 'state/kwara/federal-university-of-health-sciences-azare/' },
  aatu: { id: 'aatu', state: 'Kwara State', name: 'AATU', institution: 'Abdulrasq Abubakar Toyyin University', logo: 'image/university-logo/aatulogo.jpg', description: 'ILM Nexus AATU Campus is a campus community for learning, collaboration, and future-ready skills.', programs: [], route: 'state/kwara/aatu/' },
  'federal-polytechnic-offa': { id: 'federal-polytechnic-offa', state: 'Kwara State', name: 'Federal Polytechnic Offa', institution: 'Federal Polytechnic Offa', logo: 'image/university-logo/fpdlogo.jpg', description: 'ILM Nexus Federal Polytechnic Offa Campus connects technical learning with practical digital skills.', programs: [], route: 'state/kwara/federal-polytechnic-offa/' },
  unilag: { id: 'unilag', state: 'Lagos State', name: 'UNILAG', institution: 'University of Lagos', logo: 'image/university-logo/University of Lagoslogo.jpg', description: 'ILM Nexus UNILAG Campus is a student-led space for digital skills, innovation, and opportunity.', programs: ['Data Analytics', 'AI & Automation', 'UI/UX Design', 'Cybersecurity', 'Digital Marketing'], route: 'state/lagos/unilag/' },
  lasu: { id: 'lasu', state: 'Lagos State', name: 'LASU', institution: 'Lagos State University', logo: 'image/university-logo/LASUlogo.jpg', description: 'ILM Nexus LASU Campus helps learners turn practical skills into visible work and opportunity.', programs: ['Digital Marketing', 'Graphics Design', 'Content Creation'], route: 'state/lagos/lasu/' },
  yabatech: { id: 'yabatech', state: 'Lagos State', name: 'YABATECH', institution: 'Yaba College of Technology', logo: 'image/university-logo/YABATECHlogo.jpg', description: 'ILM Nexus YABATECH Campus brings technology, creative practice, and career development together.', programs: ['Frontend Development', 'Video Editing', 'AI Automation'], route: 'state/lagos/yabatech/' },
  'federal-school-of-survey': { id: 'federal-school-of-survey', state: 'Oyo State', name: 'Federal School of Survey', institution: 'Federal School of Surveying, Oyo', logo: 'image/university-logo/fss oyo.jpg', description: 'ILM Nexus Federal School of Survey Campus supports practical digital learning and campus community.', programs: ['Graphics Design', 'Digital Marketing', 'Programme Management'], route: 'state/oyo/federal-school-of-survey/' }
};
